# Copyright (c) 2017 by General Electric Company. All rights reserved.

# The copyright to the computer software herein is the property of
# General Electric Company. The software may be used and/or copied only
# with the written permission of General Electric Company or in accordance
# with the terms and conditions stipulated in the agreement/contract
# under which the software has been supplied.

FROM ARG_FROM

MAINTAINER Joel Markham <joel.markham@ge.com>

ADD bin/ARG_ARCH/ARG_NAME /ARG_NAME

USER nobody:nobody
ENTRYPOINT ["/ARG_NAME"]
